notreddit/config/routes.rb
Rails.application.routes.draw do

  root "subs#index"

  resource :session,  only: [:new, :create, :destroy]
  resources :users
  resources :subs
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
  end
  
  resources :comments, only: [:create]


  # You can have the root of your site routed with "root"
  # root 'welcome#index'



  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

notreddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator, class_name: "User"
  has_many :post_subs
  has_many :posts, through: :post_subs
end

notreddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_moderator, only: [:edit, :destroy, :update]
  before_action :require_logged_in, only: [:new, :create]

  def new
    @sub =  Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:error] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = current_sub
    render :edit
  end

  def update
    @sub = current_sub
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:error] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    render :index
  end

  def show
    @sub = current_sub
    render :show
  end

  def destroy
    current_sub.destroy
    redirect_to subs_url
  end

  def current_sub
    Sub.find_by_id(params[:id])
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def ensure_moderator
    unless current_user == current_sub.moderator
      flash[:error] = ["You must be the moderator to do that!"]
      redirect_to sub_url(current_sub)
    end
  end
end

notreddit/app/helpers/subs_helper.rb
module SubsHelper
end

notreddit/app/views/subs/_form.html.erb
<input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">

<label>Title<br>
  <input type="text" name="sub[title]" value="<%= @sub.title %>">
</label>
<br>

<label>Description<br>
  <textarea name="sub[description]"><%= @sub.description %></textarea>
</label>
<br>

notreddit/app/views/subs/edit.html.erb
<h1>Edit your sub</h1>
<br>
<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <%= render "form" %>

  <input type="submit" value="Edit it!">
</form>

notreddit/app/views/subs/index.html.erb
<h1>All the subs:</h1>
<br>
<ul>
  <% Sub.all.each do |sub| %>
    <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
</ul>
<br>
<%= button_to "Make a new sub!", new_sub_url, method: :get %>

notreddit/app/views/subs/new.html.erb
<h1>Make a new Sub!</h1>
<br>
<form action="<%= subs_url %>" method="post">

  <%= render "form" %>

  <input type="submit" value="Make it!">
</form>

notreddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>
<br>
<ul>
  <% @sub.posts.each do |post| %>
    <li><%= link_to post.title, post_url(post) %></li>
  <% end %>
</ul>
<br>
<%= button_to "Make a new post!", new_post_url, method: :get %>
<br>
<% if current_user == @sub.moderator %>
  <%= button_to "Edit this sub", edit_sub_url(@sub), method: :get %>
  <br> <br>
  <%= button_to "Delete this sub??? : (", sub_url(@sub), method: :delete %>
<% end %>