notreddit/config/routes.rb
Rails.application.routes.draw do

  root "subs#index"

  resource :session,  only: [:new, :create, :destroy]
  resources :users
  resources :subs
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
  end
  
  resources :comments, only: [:create]


  # You can have the root of your site routed with "root"
  # root 'welcome#index'



  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

notreddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NotReddit</title>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <h2>Logged in as <%= current_user.username %> </h2>
    <div><%= button_to "Log out", session_url, method: :delete %></div>
  <% else %>
    <div><%= button_to "Log in", new_session_url, method: :get %></div>
  <% end %>

  <ul>
    <% flash[:error] ||= []
       flash[:error].each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
  </ul>

<%= yield %>
<br>

<div>
  <%= link_to "Back to Main Sub List", subs_url %>
  <br>
  <%= link_to "Your user page", user_url(current_user) if logged_in? %>
</div>

</body>
</html>